.PHONY: test-c
test-c:
	python ./cPyparsing_test.py

.PHONY: test-py
test-py:
	powershell ./pyparsing_test.ps1

.PHONY: test-coconut-py
test-coconut-py:
	powershell ./coconut_pyparsing_test.ps1

.PHONY: test-coconut-c
test-coconut-c:
	powershell ./coconut_cPyparsing_test.ps1
